import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Layout1 from "../components/Layout1";
import Layout2 from "../components/Layout2";
import Draggable from "react-draggable";
import { Component, useState } from "react";

export default function Home() {
  let [components, setComponents] = useState();
  function onDragStart(event) {
    // console.log(event.dataTransfer);
    event.dataTransfer.setData("text/plain", event.target.id);
    console.log(event.target.id);
    event.dataTransfer.effectAllowed = "copy";
  }
  function allowDrop(event) {
    event.preventDefault();
  }
  function onDrop(event) {
    // const draggableElement = document.getElementById(id).cloneNode(true);
    // draggableElement.id = "newId";
    // dropZone.appendChild(draggableElement);
    // event.dataTransfer.clearData();
    // const dropZone = event.target;

    const id = event.dataTransfer.getData("text");
    console.log("id", id);
    if (id == "layout1") {
      setComponents(<Layout1 isShowContent={true}></Layout1>);
    }
    if (id == "layout2") {
      setComponents(<Layout2 isShowContent={true}></Layout2>);
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.layoutContainer}>
          <div className={styles.layoutLeftMenu}>
            <div className={styles.layoutStore}>
              <div className={styles.layout}>
                <Layout1 onDragStart={onDragStart}></Layout1>
              </div>
              <div className={styles.layout}>
                <Layout2 onDragStart={onDragStart}></Layout2>
              </div>
              <div className={styles.layout}>
                <Layout2 onDragStart={onDragStart}></Layout2>
              </div>
            </div>
          </div>
          <div className={styles.layoutRight}>
            <div
              className={styles.collageLayoutContainer}
              onDragOver={allowDrop}
              onDrop={onDrop}
            >
              {components ? components : ""}
            </div>
          </div>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
